PKGDATADIR = "Set at build time"
VERSION = "Set at build time"
APP_ID = "Set at build time"
RESOURCE_PATH = "Set at build time"
NWJS_DIR = "Set at build time"
LOCALE_DIR = "Set at build time"
assert False, "This file is for type hinting only; do not execute it directly."